package com.example.demo;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

@Service
public class service_TagService {
    
	public List<entity_TagDTO> getTag()
	{
		List<entity_TagDTO> etst=new ArrayList<entity_TagDTO>();
		 entity_TagDTO et=new entity_TagDTO();
		 et.setCategoryname("country");
		 List<String> showtagst=new ArrayList<String>();
		 List<String> valuetagst=new ArrayList<String>();
		 showtagst.add("🇺🇸");
		 valuetagst.add("United States");
		 showtagst.add("🇨🇳");
		 valuetagst.add("China");
		 showtagst.add("🇮🇳");
		 valuetagst.add("India");
		 showtagst.add("🇷🇺");
		 valuetagst.add("Russia");
		 showtagst.add("🇩🇪");
		 valuetagst.add("Germany");
		 showtagst.add("🇬🇧");
		 valuetagst.add("United Kingdom");
		 showtagst.add("🇯🇵");
		 valuetagst.add("Japan");
		 showtagst.add("🇫🇷");
		 valuetagst.add("France");
		 showtagst.add("🇧🇷");
		 valuetagst.add("Brazil");
		 showtagst.add("🇮🇹");
		 valuetagst.add("Italy");
		 showtagst.add("🇪🇸");
		 valuetagst.add("Spain");
		 showtagst.add("🇦🇺");
		 valuetagst.add("Australia");
		 showtagst.add("🇨🇦");
		 valuetagst.add("Canada");
		 showtagst.add("🇸🇪");
		 valuetagst.add("Sweden");
		 showtagst.add("🇧🇪");
		 valuetagst.add("Belgium");
		 showtagst.add("🇳🇱");
		 valuetagst.add("Netherlands");
		 showtagst.add("🇰🇷");
		 valuetagst.add("South Korea");
		 showtagst.add("🇺🇳");
		 valuetagst.add("Other country");
		 et.setShowTags(showtagst);
		 et.setValueTags(valuetagst);
		 entity_TagDTO et2=new entity_TagDTO();
		 et2.setCategoryname("topic");
		 List<String> showtagst2=new ArrayList<String>();
		 List<String> valuetagst2=new ArrayList<String>();
		 showtagst2.add("🏰");
		 valuetagst2.add("political");
		 showtagst2.add("⚖️");
		 valuetagst2.add("legal");
		 showtagst2.add("🚀");
		 valuetagst2.add("military");
		 showtagst2.add("🎢");
		 valuetagst2.add("entertainment");
		 showtagst2.add("🛰");
		 valuetagst2.add("Technology");
		 showtagst2.add("🚗️");
		 valuetagst2.add("society");
		 showtagst2.add("💰");
		 valuetagst2.add("economic");
		 et2.setShowTags(showtagst2);
		 et2.setValueTags(valuetagst2);
		 entity_TagDTO et3=new entity_TagDTO();
		 et3.setCategoryname("political");
		 List<String> showtagst3=new ArrayList<String>();
		 List<String> valuetagst3=new ArrayList<String>();
		 showtagst3.add("personage");
		 valuetagst3.add("personage");
		 showtagst3.add("current politics");
		 valuetagst3.add("current politics");
		 showtagst3.add("information disclosure");
		 valuetagst3.add("information disclosure");
		 showtagst3.add("Political history");
		 valuetagst3.add("Political history");
		 showtagst3.add("Other");
		 valuetagst3.add("Other");
		 et3.setShowTags(showtagst3);
		 et3.setValueTags(valuetagst3);
		 entity_TagDTO et4=new entity_TagDTO();
		 et3.setCategoryname("legal");
		 List<String> showtagst4=new ArrayList<String>();
		 List<String> valuetagst4=new ArrayList<String>();
		 showtagst4.add("personage");
		 valuetagst4.add("personage");
		 showtagst4.add("Sentence");
		 valuetagst4.add("Sentence");
		 showtagst4.add("article");
		 valuetagst4.add("article");
		 showtagst4.add("National law");
		 valuetagst4.add("National law");
		 showtagst4.add("local law");
		 valuetagst4.add("local law");
		 showtagst4.add("other");
		 valuetagst4.add("other");
		 et4.setShowTags(showtagst4);
		 et4.setValueTags(valuetagst4);
		 entity_TagDTO et5=new entity_TagDTO();
		 et5.setCategoryname("military");
		 List<String> showtagst5=new ArrayList<String>();
		 List<String> valuetagst5=new ArrayList<String>();
		 showtagst5.add("personage");
		 valuetagst5.add("personage");
		 showtagst5.add("war");
		 valuetagst5.add("war");
		 showtagst5.add("arms");
		 valuetagst5.add("arms");
		 showtagst5.add("conflict");
		 valuetagst5.add("conflict");
		 showtagst5.add("other");
		 valuetagst5.add("other");
		 et5.setShowTags(showtagst5);
		 et5.setValueTags(valuetagst5);
		 entity_TagDTO et6=new entity_TagDTO();
		 et6.setCategoryname("Technology");
		 List<String> showtagst6=new ArrayList<String>();
		 List<String> valuetagst6=new ArrayList<String>();
		 showtagst6.add("personage");
		 valuetagst6.add("personage");
		 showtagst6.add("Internet");
		 valuetagst6.add("Internet");
		 showtagst6.add("artificial intelligence");
		 valuetagst6.add("artificial intelligence");
		 showtagst6.add("discover");
		 valuetagst6.add("discover");
		 showtagst6.add("theory");
		 valuetagst6.add("theory");
		 showtagst6.add("explore");
		 valuetagst6.add("explore");
		 showtagst6.add("other");
		 valuetagst6.add("other");
		 et6.setShowTags(showtagst6);
		 et6.setValueTags(valuetagst6);
		 entity_TagDTO et7=new entity_TagDTO();
		 et7.setCategoryname("society");
		 List<String> showtagst7=new ArrayList<String>();
		 List<String> valuetagst7=new ArrayList<String>();
		 showtagst7.add("personage");
		 valuetagst7.add("personage");
		 showtagst7.add("Crime");
		 valuetagst7.add("Crime");
		 showtagst7.add("education");
		 valuetagst7.add("education");
		 showtagst7.add("Healthy");
		 valuetagst7.add("Healthy");
		 showtagst7.add("Culture");
		 valuetagst7.add("Culture");
		 showtagst7.add("Eco climate");
		 valuetagst7.add("Eco climate");
		 showtagst7.add("Social news");
		 valuetagst7.add("Social news");
		 showtagst7.add("Strange news");
		 valuetagst7.add("Strange news");
		 showtagst7.add("other");
		 valuetagst7.add("other");
		 et7.setShowTags(showtagst7);
		 et7.setValueTags(valuetagst7);
		 entity_TagDTO et8=new entity_TagDTO();
		 et8.setCategoryname("economic");
		 List<String> showtagst8=new ArrayList<String>();
		 List<String> valuetagst8=new ArrayList<String>();
		 showtagst8.add("personage");
		 valuetagst8.add("personage");
		 showtagst8.add("business");
		 valuetagst8.add("business");
		 showtagst8.add("Bank");
		 valuetagst8.add("Bank");
		 showtagst8.add("enterprise");
		 valuetagst8.add("enterprise");
		 showtagst8.add("data");
		 valuetagst8.add("data");
		 showtagst8.add("other");
		 valuetagst8.add("other");
		 et8.setShowTags(showtagst8);
		 et8.setValueTags(valuetagst8);
		 
		 entity_TagDTO et9=new entity_TagDTO();
		 et9.setCategoryname("entertainment");
		 List<String> showtagst9=new ArrayList<String>();
		 List<String> valuetagst9=new ArrayList<String>();
		 showtagst9.add("personage");
		 valuetagst9.add("personage");
		 showtagst9.add("physical culture");
		 valuetagst9.add("physical culture");
		 showtagst9.add("Variety");
		 valuetagst9.add("Variety");
		 showtagst9.add("Game");
		 valuetagst9.add("Game");
		 showtagst9.add("other");
		 valuetagst9.add("other");
		 
		 et9.setShowTags(showtagst9);
		 et9.setValueTags(showtagst9);
		 
		 
		 
		 etst.add(et);
		 etst.add(et2);
		 etst.add(et3);
		 etst.add(et4);
		 
		 etst.add(et5);
		 etst.add(et6);
		 etst.add(et7);
		 etst.add(et8);
		 etst.add(et9);
		 return etst;
		 
	}
}
